const specialtyData = {
    "Berry":{
        "natures":{
            "Adamant":1.0,
            "Bashful":0.5,
            "Bold":0.0,
            "Brave":0.9,
            "Calm":0.1,
            "Careful":0.6,
            "Docile":0.5,
            "Gentle":0.5,
            "Hardy":0.5,
            "Hasty":0.6,
            "Impish":0.5,
            "Jolly":0.8,
            "Lax":0.5,
            "Lonely":0.9,
            "Mild":0.1,
            "Modest":0.0,
            "Naive":0.6,
            "Naughty":0.9,
            "Quiet":0.0,
            "Quirky":0.5,
            "Rash":0.1,
            "Relaxed":0.2,
            "Sassy":0.2,
            "Serious":0.5,
            "Timid":0.1
        },
        "subskills":{
            "Berry Finding S":1.0,
            "Dream Shard Bonus":0.2,
            "Energy Recovery Bonus":0.1,
            "Helping Bonus":0.7,
            "Helping Speed S":0.4,
            "Helping Speed M":0.5,
            "Ingredient Finder S":0.0,
            "Ingredient Finder M":0.0,
            "Inventory Up S":0.1,
            "Inventory Up M":0.1,
            "Inventory Up L":0.1,
            "Research EXP Bonus":0.1,
            "Skill Level Up S":0.1,
            "Skill Level Up M":0.3,
            "Skill Trigger S":0.2,
            "Skill Trigger M":0.3,
            "Sleep EXP Bonus":0.2
        },
        "ratingWeights":{
            "nature":0.15,
            "subskills":0.70,
            "ingredients":0,
            "tierlist":0.15
        }
    },
    "Ingredient":{
        "natures":{
            "Adamant":0.1,
            "Bashful":0.5,
            "Bold":0.1,
            "Brave":0.7,
            "Calm":0.1,
            "Careful":0.1,
            "Docile":0.5,
            "Gentle":0.5,
            "Hardy":0.5,
            "Hasty":0.5,
            "Impish":0.0,
            "Jolly":0.1,
            "Lax":0.5,
            "Lonely":0.6,
            "Mild":0.9,
            "Modest":0.7,
            "Naive":0.5,
            "Naughty":0.7,
            "Quiet":1.0,
            "Quirky":0.5,
            "Rash":1.0,
            "Relaxed":0.4,
            "Sassy":0.2,
            "Serious":0.5,
            "Timid":0.1
        },
        "subskills":{
            "Berry Finding S":0.5,
            "Dream Shard Bonus":0.3,
            "Energy Recovery Bonus":0.2,
            "Helping Bonus":0.9,
            "Helping Speed S":0.5,
            "Helping Speed M":0.7,
            "Ingredient Finder S":0.8,
            "Ingredient Finder M":1.0,
            "Inventory Up S":0.4,
            "Inventory Up M":0.5,
            "Inventory Up L":0.6,
            "Research EXP Bonus":0.2,
            "Skill Level Up S":0.2,
            "Skill Level Up M":0.3,
            "Skill Trigger S":0.3,
            "Skill Trigger M":0.4,
            "Sleep EXP Bonus":0.3
        },
        "ratingWeights":{
            "nature":0.15,
            "subskills":0.55,
            "ingredients":0.2,
            "tierlist":0.1
        }
    },
    "Skill":{
        "natures":{
            "Adamant":0.7,
            "Bashful":0.5,
            "Bold":0.1,
            "Brave":0.7,
            "Calm":0.6,
            "Careful":1.0,
            "Docile":0.5,
            "Gentle":0.9,
            "Hardy":0.5,
            "Hasty":0.5,
            "Impish":0.5,
            "Jolly":0.5,
            "Lax":0.0,
            "Lonely":0.6,
            "Mild":0.2,
            "Modest":0.1,
            "Naive":0.1,
            "Naughty":0.2,
            "Quiet":0.2,
            "Quirky":0.5,
            "Rash":0.0,
            "Relaxed":0.4,
            "Sassy":1.0,
            "Serious":0.5,
            "Timid":0.1
        },
        "subskills":{
            "Berry Finding S":0.7,
            "Dream Shard Bonus":0.3,
            "Energy Recovery Bonus":0.2,
            "Helping Bonus":0.9,
            "Helping Speed S":0.5,
            "Helping Speed M":0.7,
            "Ingredient Finder S":0.0,
            "Ingredient Finder M":0.0,
            "Inventory Up S":0.2,
            "Inventory Up M":0.3,
            "Inventory Up L":0.4,
            "Research EXP Bonus":0.2,
            "Skill Level Up S":0.3,
            "Skill Level Up M":0.5,
            "Skill Trigger S":0.8,
            "Skill Trigger M":1.0,
            "Sleep EXP Bonus":0.3
        },
        "ratingWeights":{
            "nature":0.2,
            "subskills":0.6,
            "ingredients":0,
            "tierlist":0.2
        }
    },
    "SkillPower":{
        "natures":{
            "Adamant":0.8,
            "Bashful":0.5,
            "Bold":0.0,
            "Brave":0.8,
            "Calm":0.5,
            "Careful":1.0,
            "Docile":0.5,
            "Gentle":0.9,
            "Hardy":0.5,
            "Hasty":0.5,
            "Impish":0.5,
            "Jolly":0.6,
            "Lax":0.0,
            "Lonely":0.7,
            "Mild":0.1,
            "Modest":0.0,
            "Naive":0.1,
            "Naughty":0.3,
            "Quiet":0.1,
            "Quirky":0.5,
            "Rash":0.0,
            "Relaxed":0.3,
            "Sassy":1.0,
            "Serious":0.5,
            "Timid":0.0
        },
        "subskills":{
            "Berry Finding S":0.9,
            "Dream Shard Bonus":0.3,
            "Energy Recovery Bonus":0.2,
            "Helping Bonus":0.9,
            "Helping Speed S":0.6,
            "Helping Speed M":0.7,
            "Ingredient Finder S":0.0,
            "Ingredient Finder M":0.0,
            "Inventory Up S":0.2,
            "Inventory Up M":0.3,
            "Inventory Up L":0.4,
            "Research EXP Bonus":0.2,
            "Skill Level Up S":0.3,
            "Skill Level Up M":0.5,
            "Skill Trigger S":0.8,
            "Skill Trigger M":1.0,
            "Sleep EXP Bonus":0.3
        },
        "ratingWeights":{
            "nature":0.2,
            "subskills":0.65,
            "ingredients":0,
            "tierlist":0.15
        }
    }
}
